### ISSUE TITLE
Question: Will a 1.19.4 world with GBW be able to update to 1.20?

### ISSUE THREAD

**Issue by VeggeieDude** [great-big-world/great-big-world#10]
Hey! I was wondering if I made a world with this mod on 1.19.4, would i be able to update to 1.20 once you update the mod to that version?

**Comment by jack-zisa** [comment]
It should be able to update without issue. The new update only adds 1 new biome which doesn't affect any biomes added in GBW, and the new tropical islands in GBW 1.2.0 are done separately. If any issues do occur, I'll be sure to iron them out asap!
