### ISSUE TITLE
Lavarock converting to grassy lavarock non stop

### ISSUE THREAD

**Issue by MagikUnicorn** [great-big-world/great-big-world#13]
I used /gamerule randomtickspeed 100 to make it more apparent
https://github.com/great-big-world/great-big-world/assets/16508989/3a3dd053-39ea-4d74-98ff-1435bb796bcd

Also idk if it's a bug but over time every lavarock exposed to air on top transform to grassy one making volcanic crater lush

**Comment by MagikUnicorn** [comment]
Using :
-CreoLib-1.19.4-1.0.0-beta.9
-TerraBlender-fabric-1.19.4-2.2.0.158
-fabric-api-0.83.0+1.19.4
-great-big-world-1.19.4-1.2.2
 and some other mods btw, ask me if you need anything

**Comment by jack-zisa** [comment]
Just released a new version which fixed this error when tested. If you still notice it, just open a new issue. And thanks for the bug report!
