### ISSUE TITLE
feature cycle: regions_unexplored:autumnal_maple_forest and great_big_world:snowy_aspen_forest

### ISSUE THREAD

**Issue by stunlocked1** [great-big-world/great-big-world#15]
https://gist.github.com/stunlocked1/5db521adc0a25d3e010229debff635b9

**Comment by jack-zisa** [comment]
Putting out a new 1.19.2 version soon with this fix as well as some more mod compat.

**Comment by jack-zisa** [comment]
New version released. This issue should be fixed. Feel free to reopen this if it isn't!
