### ISSUE TITLE
1.19.2?

### ISSUE THREAD

**Issue by ereese99** [great-big-world/great-big-world#2]
I'm a big fan of your mods but this mod isn't available for 1.19.2, any plans on making it compatible?

**Comment by VeggeieDude** [comment]
I second this if you ever get time for it!

**Comment by Puffadillo** [comment]
Also seconding this if you ever get the time to backport; 1.19.2 seems to be the "standard" version for The Wild Update. I'll likely never be able to move to 1.19.3 due to about 15% of the mods in my pack breaking and needing revisions that their developers may not have time to fix.

**Comment by jack-zisa** [comment]
Yeah I've noticed most people and mods are staying on 1.19.2. The good news is that with the fix of the previous issue, I think I can release a passable version of Great Big World for 1.19.2. I may actually release it tonight lol.
