### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by MartialEmperor** [great-big-world/great-big-world#3]
i wanna try the mod but it crash on startup 

mc ver - 1.19.3
fabric version - fabric-api-0.73.0+1.19.3
terrablender - i tried TerraBlender-fabric-1.19.3-2.1.0.134 and TerraBlender-fabric-1.19.3-2.1.0.139 the latest one

do tell if its my problem in my end.. first time i added mods in MC so idk how it works

[crash-2023-01-25_19.55.23-client.txt](https://github.com/great-big-world/great-big-world/files/10499165/crash-2023-01-25_19.55.23-client.txt)

**Comment by jack-zisa** [comment]
this is an issue on my end, I'm looking into ot right now. I will release a hotfix as soon as I resolve this 👍

**Comment by jack-zisa** [comment]
Should be resolved now, I just released a new version on Modrinth and Curseforge. Let me know if this issue persists, otherwise I'll close it in a few days.

**Comment by MartialEmperor** [comment]
> Should be resolved now, I just released a new version on Modrinth and Curseforge. Let me know if this issue persists, otherwise I'll close it in a few days.

it works now thank you :)
