### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by Puffadillo** [great-big-world/great-big-world#4]
Minecraft `1.19.3`
Fabric Loader `0.14.14`
Fabric API `0.74.0`
TerraBlender `2.1.0.139`
Great Big World `1.1.1`
Crash report: https://gist.github.com/Puffadillo/3d3ee26c80d34c4bbc06a22ddf7fbaf1

Tested on a fresh instance with only the above mods; game crashes immediately on launch.

**Comment by jack-zisa** [comment]
This issue is fixed, however the mod will still require Cloth Config & Mod Menu to run. I am working on making them completely optional.
