### ISSUE TITLE
Music disc not playing in jukebox

### ISSUE THREAD

**Issue by Puffadillo** [great-big-world/great-big-world#6]
Minecraft `1.19.2`
Fabric loader `0.14.14`
Fabric API `0.73.2`
Cloth Config `8.2.88`
Mod Menu `4.1.2`
TerraBlender `2.0.1.136`
Great Big World `1.1.2`

Very minor issue I noticed: when the new music disc "Sunrise" is used on a jukebox, it's being placed inside but no sound plays and no song subtitle appears on screen. Also not sure if it's an intentional design choice, but the "Thicket" skeleton mob plays generic player hit sounds. Good mod though, I know it's early on in development but am documenting these in case it's helpful.

**Comment by jack-zisa** [comment]
Thanks for letting me know, will be fixing these asap!
